# Generated by Django 5.0.4 on 2024-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0004_alter_student_email_alter_trainer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, verbose_name='ФИО')),
                ('email', models.CharField(default='', max_length=255, verbose_name='Email')),
                ('skills', models.CharField(default='', max_length=255, verbose_name='Навыки')),
                ('password', models.CharField(max_length=255)),
                ('number', models.CharField(default='', max_length=255, verbose_name='Телефон')),
                ('user_type', models.IntegerField(choices=[(1, 'Тренер'), (2, 'Студент')], default=2, verbose_name='Тип пользователя')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
