# Generated by Django 5.0.4 on 2024-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0005_user_delete_student_delete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_address',
            field=models.TextField(default='г. Екатеринбург, ул. Мира 32', verbose_name='Адрес клуба'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(default='', verbose_name='Образование'),
        ),
    ]
