# Generated by Django 5.0.4 on 2024-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0006_user_club_address_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(default='', max_length=255, verbose_name='Навыки'),
        ),
    ]
