# Generated by Django 5.0.4 on 2024-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0007_user_description_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(default='', verbose_name='Достижения'),
        ),
    ]
