# Generated by Django 5.0.4 on 2024-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0008_user_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
