# Generated by Django 5.0.4 on 2024-05-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0009_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Студент'), (2, 'Тренер')], default=1, verbose_name='Тип пользователя'),
        ),
    ]
