# Generated by Django 5.0.4 on 2024-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0011_user_students_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups_id',
            field=models.TextField(blank=True, default='[]', verbose_name='ID групп'),
        ),
    ]
