# Generated by Django 5.0.4 on 2024-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_screen', '0013_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule_str',
            field=models.TextField(blank=True, default='Расписание отсутствует', verbose_name='Расписание'),
        ),
    ]
