# Generated by Django 5.0.4 on 2024-05-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_screen', '0009_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('schedule_time_start', models.TimeField()),
                ('schedule_time_end', models.TimeField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to='registration_screen.user')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_schedules', to='registration_screen.user')),
            ],
        ),
    ]
